Dev
asyriac/flixcart pull request #1
Opened 2021-05-05 08:45 UTC by asyriac

2021-05-06 05:16 UTC, Aravindan07 requested changes
Hey, Arun Your application looks good. I have some changes to incorporate into your application.

1. Update the REAME.md file in Github.
2. I can add an item to the cart even though it is mentioned as out of stock. Fix this!
3.  Right now the wishlist icon appearing only on hover and also the icon size is too small. A user doesn't know if the particular item is on the wishlist or not if you plan to show the wishlist icon on hover. This is just a suggestion it's your wish to change it.
4.  Place the + button on the right and - button on the left you did the opposite. The reason to change this is that most of the users are right-handers so it would better if you place the - button on the right side.
5. It is showing the move to cart option for an item that is already added to the cart when that particular item is present in the wishlist. Fix this.
6.  You are allowing the same product to be added multiple times in the cart instead what you can do is increment the quantity of the product if it is added more than one time.
7. Change the title from React App to your application name.

2021-05-06 05:16 UTC, Aravindan07 commented on src/utils/utils.js
> +    // return arr;
Remove the comments

2021-05-06 05:16 UTC, Aravindan07 commented on src/components/ProductList.js
> +    console.log(products[0]);
Remove the log statements

2021-05-06 05:16 UTC, Aravindan07 commented on src/components/WishlistItem.js
> +            <img className="card-img-h" src={image} alt="" />
alt attribute is empty

2021-05-06 07:58 UTC, sjsouvik requested changes
Hi Arun,

The code looks clean, here're few suggestions from my end -

- remove default README
- add _redirects in public folder so that can prevent page not found error in netlify while you visit a route or refresh a route, let me know if you need more details on this
- add toasts to show some message on actions
- make it mobile responsive
- remove commented code and console log statements once the feature implementation is done

2021-05-06 07:58 UTC, sjsouvik commented on src/App.js
> +      <Route path="/wishlist" exact component={WishlistPage} />
Add route for 404 Not found

2021-05-21 16:15 UTC, khusharth commented
- Loading can be placed in the center
- Filters UI can be better (optional)
- Can add search here
- Can use badge component from component library for fast delivery 
- https://flixcart.netlify.app/wishlist: There should be a wishlist heading on this page
- In the end of the website, Have some space or add a footer.
- On delete (optional): On delete have a confirmation modal.
- After any operation delete, add to card etc show an alert.
- Update the favicon on the project 
- Make Navbar, filter, cart page responsive.
- spacing can be improved in Price details on the Cart page

# BUG
- Move to cart button clears all wishlist

Optional features:
- Pagination

2022-07-22 07:56 UTC, merged